### ISSUE TITLE
Edit text strings or german translations for plugin

### ISSUE THREAD

**Issue by newbie-2004** [Zeichen32/PiwikCustomOptOut#20]
hi,
i had tried to modify the german translations for your plugin in different .json files (add to /lang/de.json, add to /plugin/CoreAdminHome/lang/ & /plugin/CustomOptOut/lang/), but don't get a result.
i'm using piwik in the newest version 2.9.1.
hope you can help!?
br,
newbie-2004

**Comment by Zeichen32** [comment]
Fix in Version (0.2.0) https://github.com/Zeichen32/PiwikCustomOptOut/tree/0.2.0
