### ISSUE TITLE
escaped path to external css file

### ISSUE THREAD

**Issue by wgruenberger** [Zeichen32/PiwikCustomOptOut#22]
Hi,
i installed the plugin and entered the custom css, which works fine.

But i need to do some more tweaks why i tried to enter a path in "external css file", unfortunately the text in the html is escaped like:
http&#x3A;&#x2F;&#x2F;www.domain.de&#x2F;wpcontent&#x2F;themes&#x2F;
and so the css can not be found.
I also just upgraded to piwik 2.11.1, maybe the escaping happens somewhere there? Can you give me a hint where to look?

**Comment by Zeichen32** [comment]
Fixed in version 0.2.3

**Comment by wgruenberger** [comment]
works like a charm, thank you!
