### ISSUE TITLE
broken piwik v2.12.0

### ISSUE THREAD

**Issue by Patta** [Zeichen32/PiwikCustomOptOut#24]
Piwik Output after update to 2.12.0

Fatal error: Call to undefined method Piwik\Menu\MenuTop::addEntry() in /xxx/piwik/plugins/ExampleUI/ExampleUI.php on line 48
A fatal error occurred

The following error just broke Piwik (v2.12.0):

Call to undefined method Piwik\Menu\MenuTop::addEntry()
in
/xxx/piwik/plugins/ExampleUI/ExampleUI.php line 48

i this an piwik or customoptout Problem?

**Comment by Zeichen32** [comment]
This is a error in the ExampleUI Plugin. You should disable the example plugins.

**Comment by Patta** [comment]
ok, thanks!
