### ISSUE TITLE
Not compatible with Piwik 2.12.1

### ISSUE THREAD

**Issue by simison** [Zeichen32/PiwikCustomOptOut#27]
>Warning:  The following plugins are not compatible with Piwik 2.12.1 and could not be loaded: CustomOptOut.

**Comment by Zeichen32** [comment]
Its curious on my servers this plugin runs without any problems with piwik 2.12.1. 
Please try to clear all caches and reinstall the plugin.

**Comment by Zeichen32** [comment]
@simison Is there any news on this issue?

**Comment by simison** [comment]
Sorry, I'm on the road right now so been a lot offline.

I updated Piwik to 2.13.0 and now it just works. Weird.

BTW at "manage plugins" page it didn't show version for your plugin, just "vUnknown".
