### ISSUE TITLE
Custom opt-out not triggered when called via https

### ISSUE THREAD

**Issue by Touchwoody** [Zeichen32/PiwikCustomOptOut#28]
For security reasons some browsers don't load "http"-content within a "https"- page. So I need to call the opt-out content via https:// in the iframe. 

If I do so, the custom-opt-Out plugin does not seem to trigger, the custom css is not used. Using http:// (and convincing the browser to load the unsecure content anyway) works quite normal.

Any idea why that is?

**Comment by Zeichen32** [comment]
I suggest to use the iframe url like the following, so the browser can choose the right http protocol:

```
 //example.org/index.php?module=CustomOptOut&action=optOut&idSite=1
```

**Comment by Touchwoody** [comment]
Good guess, I already did that. 
Still, if I switch to https the custom css ist not used (https://goo.gl/yz76Jw), it works fine with http://.

**Comment by Zeichen32** [comment]
Try the following as external CSS url:
```
//sciebo.de/styles/main.css?cb=004ea63a0f15000e42404594c6fc1694 
```

**Comment by Touchwoody** [comment]
Meh. My mistake. Of course I have to load the css file with(out) http(s), too.
Thanks for your support :).
