### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by sgiehl** [Zeichen32/PiwikCustomOptOut#29]
Piwik recently started to give plugin developers the possibility to use the Piwik translation project to get translations for their plugins.
Are you interested in using it?

**Comment by Zeichen32** [comment]
Yes, i think it's a great idea to use this possibility.

**Comment by sgiehl** [comment]
Ok. I'll set up the resources

**Comment by sgiehl** [comment]
Done. As soon as some new translations are available you should be able to update them using the piwik console. See http://developer.piwik.org/guides/translations#getting-translations-for-your-plugin- for further information
