### ISSUE TITLE
Is it possible to include Google-Fonts?

### ISSUE THREAD

**Issue by uagri** [Zeichen32/PiwikCustomOptOut#30]
If I try to add a Google-Font via an external css file, Piwik appends some get-parameter:

"http://fonts.googleapis.com/css?family=PT+Sans?cb=0011da5c ..." 

This makes Google fail, because it cannot find a font named "PT SANS**?cb=0011da5c ...**"!
Is there any other possibility to include Google-Fonts?

Regards
uagri

**Comment by Zeichen32** [comment]
Please see issue #7

**Comment by Zeichen32** [comment]
@uagri Any news on this issue? Can it be closed?

**Comment by uagri** [comment]
Hi,
succeded in using your hint "issue #7":
There's an example on https://developers.google.com/fonts/docs/getting_started:
<link rel=„stylesheet“ type=„text/css“ href=„http://fonts.googleapis.com/css?family=Tangerine“>
Find tehright name for your font at google, e.g. "PT Sans". Change the link:
http://fonts.googleapis.com/css?family=PT+Sans
and put it into your brwosers URL-field. Google will respond with css code corresponding to the font you chose. Put that into custom CSS of PiwikCustomOptOut:

```
@font-face {
  font-family: 'PT Sans';
  font-style: normal;
  font-weight: 400;
  src: local('PT Sans'), local('PTSans-Regular'), url(http://fonts.gstatic.com/s/ptsans/v8/ATKpv8nLYAKUYexo8iqqrg.woff2) format('woff2'), url(http://fonts.gstatic.com/s/ptsans/v8/LKf8nhXsWg5ybwEGXk8UBQ.woff) format('woff');
}

body {
  font-family:'PT Sans', arial, sans-serif;
}
```

Yes, issue can be closed. Thanks a lot!
Regards
uagri

**Comment by fuzsin** [comment]
Can't get it to work under matomo 4(.9.0) anymore. It seems that something has changed with Google Fonts.

PT Sans Narrow URL: https://fonts.googleapis.com/css2?family=PT+Sans+Narrow

Custom CSS: 

```
@font-face {
  font-family: 'PT Sans Narrow';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/ptsansnarrow/v16/BngRUXNadjH0qYEzV7ab-oWlsbCIwR26eg.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}

body {
  font-family: 'PT Sans Narrow', sans-serif;
}
```

**Comment by Findus23** [comment]
If you really want to exclude google fonts (and keep in mind all privacy implications), you could do a CSS `@import 'https://fonts.googleapis.com/css2?family=PT+Sans+Narrow'` (https://developer.mozilla.org/en-US/docs/Web/CSS/@import).

The same would also work if you host the fonts yourself.

But if your website already includes the fonts, it is far more efficient to embed the opt-out directly into the site instead of an iFrame:
https://developer.matomo.org/guides/tracking-javascript-guide#optional-creating-a-custom-opt-out-form

**Comment by fuzsin** [comment]
> But if your website already includes the fonts, it is far more efficient to embed the opt-out directly into the site instead of an iFrame: https://developer.matomo.org/guides/tracking-javascript-guide#optional-creating-a-custom-opt-out-form

This method looks much better. I will try it out, thank you very much!
