### ISSUE TITLE
CustomOptOut does not work in IE

### ISSUE THREAD

**Issue by Cruiser13** [Zeichen32/PiwikCustomOptOut#31]
Similar to this Piwik Core issue:
https://github.com/piwik/piwik/issues/3135

If I use the original embedding method by Piwik (2.14) OptingOut works fine in IE:
index.php?module=CoreAdminHome&amp;action=optOut&amp;language=de will work, even if Piwik is installed on different domain.
If I use CustomOptOut, the checkbox will always be re-checked because the cookie is not set.
index.php?module=CustomOptOut&action=optOut&idSite=1&language=de

Any idea how to fix this for the plugin too? Maybe in the same way it got fixed in the core?

**Comment by Zeichen32** [comment]
This issue can occur with third party cookies. 
In the next few days i want to update this plugin to use the new OptOutManager.
So this plugin can use the core OptOut logic. It will be available for Piwik >= 2.14.1-b1.

https://github.com/piwik/piwik/pull/8229

**Comment by Cruiser13** [comment]
So this plugin will be deprecated and moved to piwik core soon?

**Comment by Zeichen32** [comment]
No this plugin will not be deprecated! 
The new version of this plugin just use the new OptOutManger to inject the stylesheets.
So with the new version it is possible to style the core optout view.

**Comment by Cruiser13** [comment]
I see. So the embedding iframe url will probably change to the default one again?
Do you have an ETA for this update?

Thanks for the great work so far!

**Comment by Zeichen32** [comment]
I will release the update in the next 1-2 weeks. The update will have no bc break. If piwik >=2.14.1 the iframe url will automatic redirect to the default one.

**Comment by Cruiser13** [comment]
I migrated on the new version and it actually does work SOMETIMES. But it also does sometimes ignore setting that checkbox. I can't debug this issue properly as IE has no firebug and there is nothing in the server logs. Anybody else noticed this behaviour in IE 11?

**Comment by Zeichen32** [comment]
IE has a firebug alternative. Press F12 Key ;)

**Comment by Cruiser13** [comment]
Thanks, didn't know that. Nothing shows up in the console though.
I have the latest version which should fix this bug: https://github.com/Zeichen32/PiwikCustomOptOut/issues/32
On the site however if I click the checkbox in IE, the custom CSS will disappear but the checkbox will remain checked.

**Comment by Zeichen32** [comment]
I think it's still the "Third Party Cookie" Problem which should be fixed in: https://github.com/piwik/piwik/issues/3135

**Comment by Cruiser13** [comment]
You are right, activating third party cookies does the trick in IE. https://github.com/piwik/piwik/issues/3135 should be fixed in the current piwik version 2.14.3 but seems not to be fixed. So no problem with the plugin, you can close this issue.
Thanks for your patience!
