### ISSUE TITLE
Custom CSS Code will be ignored after changing Piwik Settings on Website (Opt-In/Out)

### ISSUE THREAD

**Issue by newbie-2004** [Zeichen32/PiwikCustomOptOut#32]
Piwik 2.14.2
Custom OptOut 0.3

I'm using individual CSS code for OptOut text (inserted into CSS code editor).

When you will see Piwik setting on the website, then the popup will be shown correct format and styling.
After changing the settings, the poup will lose individual CSS code.

Can you confirm this problem?

BR,
newbie2004

**Comment by Zeichen32** [comment]
I think it is related to this issue:
https://github.com/piwik/piwik/issues/8422

Can you please post your iframe url?

**Comment by newbie-2004** [comment]
http://bit.ly/1MOKiPd

**Comment by Zeichen32** [comment]
You need to add the siteId parameter.

index.php?module=CoreAdminHome&action=optOut&language=de&***idSite=xyz***

**Comment by newbie-2004** [comment]
I had send you the preview link of the Piwik backend ...
This URL is used in the website http://bit.ly/1IkUw5H

**Comment by newbie-2004** [comment]
http://www.besucheranalyse.biz/index.php?module=CustomOptOut&action=optOut&idSite=2&language=de

**Comment by newbie-2004** [comment]
FYI: with previous version of Piwik and your plugin the above mentioned problem doesn't exist.

**Comment by Zeichen32** [comment]
No, since the first release the idSite parameter was required to determine the css code for the requested site.

**Comment by newbie-2004** [comment]
the url contains the contains the "idSite".
The correct styling will be shown, but after switching between "track" and "do-not-track" the styling will be lost.
you can try using above mentioned URL.

**Comment by Zeichen32** [comment]
Ah okay, now i see what you mean. I will have a look at this issue. ;)

**Comment by Cruiser13** [comment]
+1 with this issue.

**Comment by newbie-2004** [comment]
hi,
using latest plugin version 0.40. i'm working with popup as written above.
when first try to show tracking settings poup, it will be shown in foreground. if you change the hook for do not track your visit, then the popup will be moved to the background.
this isn't very comfortable and with older versions the issue doesn't exist.
br,
newbie2004

**Comment by Zeichen32** [comment]
In the new version, i remove the optout logic from the plugin and use the piwik core optout mechanism. 
(OptOutManager). So you should maybe better open your issue in piwik repository.

Some background:
Since modern browsers block third party cookies, piwik need to open the optout method in a new tab/window.
