### ISSUE TITLE
URL-Parameter should use &idsite= and not &idSite= (notice the case difference) 

### ISSUE THREAD

**Issue by skleiber** [Zeichen32/PiwikCustomOptOut#33]
In the log i noticed the error "Invalid idSite: '0'" and found following hint in the Piwik forum:
http://forum.piwik.org/read.php?2,115076

In one Posting (from matt, 'May 09, 2014 12:58AM'):
you should use &idsite= and not &idSite= (notice the case difference)
If you saw &idSite= somewhere in the doc let me know as we need the user guides to be correct smiling smiley

It seems like in some former Piwik version, there was accidentally idSite instead of idsite as parameter.
Since this is corrected in Piwik itself, maybe the idSite-Error comes from CustomOptOut-Plugin?

**Comment by Zeichen32** [comment]
Shure the OptOut Plugin use the idSite Parameter. I will change the typo with the next update.

**Comment by Zeichen32** [comment]
Found in documentation idSite:
http://developer.piwik.org/guides/controllers#generating-output

Found in core:
https://github.com/piwik/piwik/blob/master/core/Plugin/Menu.php#L206

https://github.com/piwik/piwik/issues/5131
