### ISSUE TITLE
Popup position will be ignored after changing Piwik Settings on Website (Opt-In/Out)

### ISSUE THREAD

**Issue by newbie-2004** [Zeichen32/PiwikCustomOptOut#35]
hi,
using latest plugin version 0.40. i'm working with popup as written above.
when first try to show tracking settings poup, it will be shown in foreground. if you change the hook for do not track your visit, then the popup will be moved to the background.
this isn't very comfortable and with older versions the issue doesn't exist.
br,
newbie2004

**Comment by Zeichen32** [comment]
See comment in #32
