### ISSUE TITLE
Tracking setting for different website won't be considered

### ISSUE THREAD

**Issue by newbie-2004** [Zeichen32/PiwikCustomOptOut#36]
hi,
i'm using self hosted version of latest piwik 2.1.5 with your latest plugin 0.40.
i have different websites with different ids.
for all sites tracking with piwik is allowed.
if you are visiting one website and change piwik setting to do-not-track and leave site then visiting another of your own website and check piwik settings here ... it is also set to do-not-track - independent of other idsite parameter.
same procedure from the other side.
br,
newbie2004

**Comment by Zeichen32** [comment]
The optout handling is managed in piwik core. So i think this issue is related to piwik and not to this plugin.
