### ISSUE TITLE
Setting css for generic opt in/out is useful

### ISSUE THREAD

**Issue by yncyrydybyl** [Zeichen32/PiwikCustomOptOut#38]
The plugin only shows css-input-fields for iframes with a site-id. But for the generic IFrame is no way to set the css.

/index.php?module=CoreAdminHome&action=optOut&language=de

There should be that possibility too. It also could work as a default for all unmodified site-ids.

**Comment by Zeichen32** [comment]
Good catch, i will work on it soon.

**Comment by Zeichen32** [comment]
Done in version 0.4.1 :+1:
