### ISSUE TITLE
You are not allowed to read the value of the setting "defaultCssStyles" in plugin "CustomOptOut"

### ISSUE THREAD

**Issue by devdesco-ceo** [Zeichen32/PiwikCustomOptOut#41]
For all unauthorized users there is an error message coming out:
You are not allowed to read the value of the setting "defaultCssStyles" in plugin "CustomOptOut"

**Comment by Zeichen32** [comment]
Should be fixed in version 0.4.2.
Can you confirm this?

**Comment by devdesco-ceo** [comment]
You are a hero!!! Thumbs up! It is working now! Thanks dude!
