### ISSUE TITLE
Reponsive height

### ISSUE THREAD

**Issue by mkoitka** [Zeichen32/PiwikCustomOptOut#42]
For responsive websites or some other special cases it would be useful to let the iFrame grow responsively in height to either avoid scroll bars or a huge vertical gap at the bottom. Technically this could be implemented with window.postMessage. 

Would this make sense or is it a too specific use case?

**Comment by xMysteriox** [comment]
I think that this feature is better suited for the Piwik core.
The CustomOptOut plugin only injects CSS into the iFrame.

Try submitting this issue to the Piwik repository.

**Comment by Zeichen32** [comment]
@mkoitka any news on this issue? Do you create a new issue in Piwik Core repository?

**Comment by mkoitka** [comment]
@Zeichen32 Yes, sorry for the delay. I will try it there. Issue might be closed.
