### ISSUE TITLE
Please extend the plugin for custom js

### ISSUE THREAD

**Issue by Matthias-Hermsdorf** [Zeichen32/PiwikCustomOptOut#43]
Hi,

we use a responsive Layout and different Languages. Piwiks predefinition says that the iframe ist 200px high and has a 600px width. We need it more dynamic.

For other iframes we use easyXDM. There the iframe content can propagate its height to the parent. But currently I see no way to add the necessary js to the iframe.

Could you extend the PiwikCustomOptOut for custom js?

br,
Matthias Hermsdorf

**Comment by Zeichen32** [comment]
Can you please provide a little bit more details and/or examples?
You can change the iFrame dimensions with plain css.

For example:
```css
iframe {
width: 100%;
height: 100%;
}
```

**Comment by Matthias-Hermsdorf** [comment]
I can set the height of an iframe in the parent document to some px height, and in some cases to 100%. But it is never 100% of the iframes content, but only a chosen value by trial.

In different languages and in and depending of the State (opted in or opted out) and on the screensize has the optOutText a different height. Giving the iframe different heights in px here is not a comfortable way.

EasyXDM establisches a socket connection between the iframe content and the iframe container. On every resize Event the Iframe propagates its body height to the iframe container. There a second script sets the height of the iframe container to its necessary value.
You can see a example here http://easyxdm.net/wp/2010/03/17/resize-iframe-based-on-content/

To use this i need to inject some js in the optOutIframe.

And in the kind of your css field/file it would be nice to see a js field/file there, which will be included in a similar way.

**Comment by Zeichen32** [comment]
Ok it should be easy to inject javascript. I will work on it if i have some time.
If you need this feature now, maybe you can work on it and create a pull request?

**Comment by Matthias-Hermsdorf** [comment]
I'm sorry. Js is my playground. For the PHP I wouldn't be usefull.
