### ISSUE TITLE
ZIP-File can not be extracted under Win7 64Bit

### ISSUE THREAD

**Issue by NickIQTIG** [Zeichen32/PiwikCustomOptOut#45]
Hi,
there is a "." (dot) in the path of the directories inside the zip-file, which makes it impossible for WinZip under Windows7 to extract the files. 7zip does the job.
Please correct.

Cheers,
Nicolai

**Comment by Zeichen32** [comment]
The recommented way to install piwik plugins is to use the piwik installation tool.

By the way, Windows 10 extract all files correctly. :smile_cat:

**Comment by NickIQTIG** [comment]
Okay. But why do you offer it for Download? No idea.
I installed the Plug-In, but nothing but the font-family has changed, even when I changed the background color of body:
body{
	font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
	font-size: 10pt;
	background-color: blue;
}
In the "preview" by Piwik everything was fine, but not in my application. Any suggestions?

**Comment by Zeichen32** [comment]
I do not offer it for Download, i have uploaded all code just on github. If you had downloaded the plugin, on the piwik homepage, maybe there is a bug on the piwik site with the zip archive.

**Comment by Zeichen32** [comment]
Have to you replace the iframe code with the new generated code?

**Comment by NickIQTIG** [comment]
Hi,
well, PIWIK offers it as direct Download: http://plugins.piwik.org/customoptout
The downloaded file is not functional with WinZip. Try it yourself under windows 7 / 8 / 9 / 10 / 11.
The CSS does only work, when I place it as "default" for all websites. The CSS for a single website does not work as shown in my previous comment.

**Comment by Zeichen32** [comment]
Unter jeder Webseite wird ein neue iFrame URL angezeigt, welche die individuelle URL der jeweiligen Seite anzeigt. Du musst die Piwik iFrame URL durch die vom Plugin austauschen.

Zum Download:
Das kann gut sein, dass das ZIP Archive auf der Piwik Seite kaputt ist, daran kann ich allerdings leider auch nichts ändern. Wenn man das Archive direkt von GitHub runterlädt, funktioniert es ohne Probleme. In der nächsten Wochen kommt aber noch die neue Version des Plugins raus, evt. funktioniert es dann mit dem Download von der Seite.
