### ISSUE TITLE
2.16.5 compatibility

### ISSUE THREAD

**Issue by Cruiser13** [Zeichen32/PiwikCustomOptOut#48]
The plugin has been deactivated in my piwik for compatibility reasons with 2.16.5 (error message _Das Plugin CustomOptOut ist nicht kompatibel mit Piwik 2.16.5_). Any plans to add 2.16.5 compatibility?

Thanks!

**Comment by Zeichen32** [comment]
On my piwik instance with version 2.17.0 the plugin run as expected. 
Maybe you can try to reinstall the plugin or clear the piwik cache.

But by the way i will work this weekend on the compatibility with piwik 3.

**Comment by Cruiser13** [comment]
Reinstalling does fix this issue, thanks!
