### ISSUE TITLE
Compatibility with Piwik 3

### ISSUE THREAD

**Issue by tsteur** [Zeichen32/PiwikCustomOptOut#49]
Hi there,

I just noticed an error when using the plugin with the latest Piwik 3.0.0-b3 version in https://github.com/Zeichen32/PiwikCustomOptOut/blob/master/Menu.php#L24

`addSettingsItem()` should be replaced with `addSystemItem()`

Here is a guide for migrating plugins to Piwik 3: http://developer.piwik.org/guides/migrate-piwik-2-to-3

You would pretty much only need to update `plugin.json` to require Piwik 3 as described in the guide and then release a new version. 

Haven't checked if there are any other problems re compatibility with Piwik 3

**Comment by Zeichen32** [comment]
The master branche is already piwik3 compatible. I will add the git tag, if piwik3 is stable. :)

**Comment by tsteur** [comment]
Awesome 👍

**Comment by Findus23** [comment]
Could you release an update, so that people will be able to upgrade without an error?
Thanks

**Comment by tsteur** [comment]
BTW: Piwik is stable now and will be released tomorrow. So releasing the update be really good

**Comment by Zeichen32** [comment]
Done 👍
