### ISSUE TITLE
Font-display in mobile Safari / iOS

### ISSUE THREAD

**Issue by E-VANCE** [Zeichen32/PiwikCustomOptOut#50]
There seems to be an issue with the display of webfonts in mobile Safari and Chrome (iOS 10.1.1) – I simply cannot get the font to display correctly although it works fine in the desktop-versions of Safari, FF, Chrome etc.

Any idea as to why this might happen? Can the plugin do anything differently or is this simply related to a security setting (preventing XSS or the like)?

--> https://thomas-knaus.de/impressum/

Thanks + regards!
Henning

**Comment by Zeichen32** [comment]
The plugin just insert the css styles into the iframe. 
Unfortunately I have no IOS device to test  this behavior.
