### ISSUE TITLE
Not working: Piwik 3.2.x

### ISSUE THREAD

**Issue by ByteBandito** [Zeichen32/PiwikCustomOptOut#52]
Plugin does not work with latest version of piwik and is disabled.

**Comment by Zeichen32** [comment]
On my piwik installation with piwik 3.2.0 the plugin work as expected.

Do you have try to reinstall the plugin?

**Comment by ByteBandito** [comment]
Its latest version and my piwik tell me:

Warnung
Folgende Plugins sind nicht kompatibel mit Piwik 3.2.0 und konnten nicht geladen werden: CustomOptOut, SecurityInfo
Sie können diese Plugins auf der Plugins verwalten Seite aktualisieren oder deinstallieren.

**Comment by Zeichen32** [comment]
Try to uninstall and then reinstall the plugin. In most cases this should fix the issue.

**Comment by ByteBandito** [comment]
Fascinating. Seems to work.... same versionnumber etc..... but it works now.
