### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by maledettobue** [Zeichen32/PiwikCustomOptOut#54]
1. is it normal my PiwikCustomOptOut only displays a CSS area (no JS)?
2. is there any way to change the HTML before it is styled? At the moment, the only thing I can really set is the font-family

**Comment by Zeichen32** [comment]
1. For security reason, you need to activate the JS Area in the plugin settings.
2. No, this plugin provide no own optout template. But you can create a theme and style the template.
https://developer.piwik.org/guides/theming#twig-the-template-engine

**Comment by maledettobue** [comment]
1. I did it, thanks;
2. the craziest thing of all is I must simply add a couple of `<p>` inside that `<iframe>`...

**Comment by Zeichen32** [comment]
No, the optout feature is provide in piwik core. This plugin just inject the css/js. So you need override the core template.

**Comment by maledettobue** [comment]
I must say I couldn't even find where the strings for every language come from: they aren't in the database, maybe some .po file or directly in a PHP file, but I could not find them

**Comment by Zeichen32** [comment]
The OptOut Template and Translation file is located in the CoreAdminHome Folder:
https://github.com/piwik/piwik/blob/3.x-dev/plugins/CoreAdminHome/templates/optOut.twig
https://github.com/piwik/piwik/blob/3.x-dev/plugins/CoreAdminHome/lang/en.json#L8

**Comment by maledettobue** [comment]
What about simply adding my `<p>` in the optOut.twig? Now that I see where are `<br>` from, I could edit this file and then apply my style using your plugin

**Comment by Zeichen32** [comment]
You need to create a Theme Plugin, if you want your changes at core templates are upgrade safe.
https://developer.piwik.org/guides/theming
