### ISSUE TITLE
Key "custom_css" for array with keys " ... " does not exist.

### ISSUE THREAD

**Issue by Seb13337** [Zeichen32/PiwikCustomOptOut#55]
Hey,
here is a Problem of mine,
everytime i try to open the Custom OPT out Tab , it shows me this Error.

I tried Clearing the OP Cache and restarting my Webserver but nothing fixed it.

`Key "custom_css" for array with keys "idsite, name, main_url, ts_created, ecommerce, sitesearch, sitesearch_keyword_parameters, sitesearch_category_parameters, timezone, currency, exclude_unknown_urls, excluded_ips, excluded_parameters, excluded_user_agents, group, type, keep_url_fragment, timezone_name, currency_name, alias_urls" does not exist. in /html/matomo/plugins/CustomOptOut/templates/index.twig 38 using PHP 7.0.29`

**Comment by Zeichen32** [comment]
It looks like your SQL Tables has not been updated. Can you try to reinstall the plugin?
