### ISSUE TITLE
Works neither with Custom CSS nor with extrenal CSS file

### ISSUE THREAD

**Issue by electricarts** [Zeichen32/PiwikCustomOptOut#56]
No matter what I enter under Custom CSS or if I place the CSS instructions in an external CSS file and use the link: The iFrame code under the input fields does not change and only shows the "normal" values. What am I doing wrong?
![screenshot 2018-12-08 at 12 05 12](https://user-images.githubusercontent.com/625286/49685303-ba00cb80-fae1-11e8-9252-7e13cef24a21.png)

**Comment by Zeichen32** [comment]
You need to use the url displayed at the bottom. At the privacy page on your website, you miss the idSite parameter, so piwik cannot identify which css styles should be load.

This is the correct url:
https://analyse.hellmann-genuss.de/index.php?module=CoreAdminHome&action=optOut&language=de&backgroundColor=&fontColor=&fontSize=&fontFamily=&idSite=1

**Comment by electricarts** [comment]
Ok. I thought that some inline styles for the CSS instructions could be found in the URL. I have now used the URL below with the idSite parameter in my privacy statement. This doesn't change the fact that neither the font size nor the font color is adjusted.

**Comment by Zeichen32** [comment]
Look at your iframe source code, the inline style is correct injected:

![image](https://user-images.githubusercontent.com/1432899/49685648-5da0aa80-fae7-11e8-8ea6-4618df990674.png)

**Comment by electricarts** [comment]
I know. Nevertheless, the wrong font is displayed in the frontend. And I don't know why.

![screenshot 2018-12-08 at 12 49 40](https://user-images.githubusercontent.com/625286/49685688-051ddd00-fae8-11e8-8fd7-dd09af31b1dd.png)

**Comment by Zeichen32** [comment]
You need to inject the Google Web Fonts in the iFrame Code. iFrames are handled as a complete separated website. 
I will close this issue, since this is a css problem and not an bug with this plugin.
