### ISSUE TITLE
Compatibility with Piwik/Matomo 3.8.1 

### ISSUE THREAD

**Issue by reissmann** [Zeichen32/PiwikCustomOptOut#58]
Since upgrading matomo to 3.8.1 it seems the plugin is no longer working :(

> Warning
> The following plugins are not compatible with Matomo 3.8.1 and could not be loaded: CustomOptOut.
> You can update or uninstall these plugins on the Manage Plugins page.

**Comment by Zeichen32** [comment]
Please try to reinstall the plugin. 
I have test it in our test systems and the plugin runs with out any issues up to the current stable 3.9.0 version of Matomo.

**Comment by reissmann** [comment]
Reinstalling fixed it. Plugin works with Matomo 3.9.1. Thank you for providing this plugin.
