### ISSUE TITLE
custom text and/or language

### ISSUE THREAD

**Issue by gour** [Zeichen32/PiwikCustomOptOut#59]
Hello,

I'm using latest (3.11.0) Matomo and would like to provide custom opt-out cookie policy on my sites. However, tried to pass `language=hr` to the 'Users opt-out' feature, but it seems it does not support Croatian language. Moreover, this plugin does not have any longer "How to change the opt-out text" ability, so wonder what do you recommend to customize Matomo's opt-out feature?

**Comment by Zeichen32** [comment]
In the market place there is a ajax opt out plugin. Maybe you can build your own opt out function.
https://plugins.matomo.org/AjaxOptOut

If you want to translate this plugin in your language, feel free to create a new Pull Request.

**Comment by gour** [comment]
> In the market place there is a ajax opt out plugin. Maybe you can build your own opt out function.

Thanks for that! Somehow, I missed it...

> If you want to translate this plugin in your language, feel free to create a new Pull Request.

Another great suggestion! ;)

**Comment by gour** [comment]
> If you want to translate this plugin in your language, feel free to create a new Pull Request.

I did investigate a bit and after I found #21 it is clear that plugin cannot provide custom text any longer, but it can only provide custom styling, right?

So, translating plugin will not provide desired functionality, 'custom language' for opt-out...

**Comment by Findus23** [comment]
Just for future reference for anyone coming across this: 
One can easily customize the opt-out text using the [Customise Translations](https://plugins.matomo.org/CustomiseTranslations) plugin.

https://peertube.floss-marketing-school.com/videos/watch/61f2929c-7d51-4c58-a4ff-f4937e7f8c02
