### ISSUE TITLE
Wrong string in original English language

### ISSUE THREAD

**Issue by KNTRO** [Zeichen32/PiwikCustomOptOut#60]
Hello!

I am localizing this plugin via Transifex and the _CustomOptOut.DefaultCssStylesDescription_ string says:

> This css styles will be used if no page is selected.

My question here is: should this string begin as _This CSS style_ or as _These CSS styles_?

Thanks!

**Comment by Zeichen32** [comment]
This is a good question. CSS is the shortcut for "Cascading Style Sheets" maybe we should omit the word "style"?

**Comment by KNTRO** [comment]
@Zeichen32 Hmph, I think you should use the word _style_ (in singular), as I think this option refers to a particular style _if no page is selected_.

**Comment by Zeichen32** [comment]
Feel free to open a pr :)

**Comment by Zeichen32** [comment]
Fixed in the next version of the plugin
