### ISSUE TITLE
Make plugin compatible with Matomo 4

### ISSUE THREAD

**Issue by Findus23** [Zeichen32/PiwikCustomOptOut#62]
Hi, hope you are doing well!

Matomo 4 is progressing steadily and it would be great if this plugin was also [available for it](https://matomo4-plugins.lw1.at/).

[Migrating the plugin](https://matomo.org/blog/2020/08/matomo4-make-your-plugin-compatible-now/) should be pretty simple as there were not many breaking changes.

You can find the migration guide here: https://developer.matomo.org/guides/migrate-matomo-3-to-4

It boils down to:
- update your dev environment to 4.x-dev
- update your plugin.json (new major version of the plugin and require `>=4.0.0-b1,<5.0.0-b1`)
- check that everything still works fine
- commit this to a new branch (e.g. `4.x-dev`) and make this branch the default in the github settings
- tag and push a new release to publish it to the marketplace

If you later fix a bug and also want to backport it to the 3.x plugin, you can cherry-pick the commit to the old branch, release a new version (lower than the one for 4.x) and publish it and 3.x users should get this update.

If you have questions about anything, just ask me!

**Comment by Zeichen32** [comment]
If update the plugin to work with the new Matomo version:
https://plugins.matomo.org/CustomOptOut?matomoversion=4

**Comment by Cruiser13** [comment]
@Zeichen32 thank you for the update! What would be the best update process? Do we need to uninstall the 3.x version of the plugin, update matomo and install the 4.x version afterwards? Will this affect the data (custom css) of the websites?

**Comment by Findus23** [comment]
There should not be any need to do anything. During the Matomo 4 update Matomo will update the plugin to the 4.x compatible version that should work just like before.
That said you should always do a proper backup beforehand.
