### ISSUE TITLE
migrate Translations to Weblate

### ISSUE THREAD

**Issue by Findus23** [Zeichen32/PiwikCustomOptOut#63]
Hi,

We are currently in the process of moving all Matomo Translations from Transifex to Weblate (see matomo-org/matomo#17907). This makes it easier for people to contribute translations, makes the process of syncing them back into the source simpler and means that we are now using Free Software for this.

We will create a Pull Request that contributes all data on Transifex up to today into this repository.

If you are interested, we can migrate this plugin to Weblate allowing people to continue to translate the strings of this plugin in their languages.
@Zeichen32, just comment and we can create the component on Weblate and set things up, so you automatically get pull requests containing the updated translations whenever they change.

**Comment by Zeichen32** [comment]
@Findus23 I think we can migrate to Weblate. Do i need to change anything in this repository?

**Comment by Findus23** [comment]
Hi,

I have created the component here: https://hosted.weblate.org/projects/matomo/communityplugin-customoptout/

Soon you should recieve a PR with the initially added languages and afterwards you should always recieve a PR with changes that you can e.g. merge before releases.

The only thing you need to do is this:
For Weblate to be notified anytime the source strings change, you need to set up a Webhook. For this go into the settings of this repository and create a new webhook with `https://hosted.weblate.org/hooks/github/` as the Payload URL. You can leave all other settings at the default.

**Comment by Zeichen32** [comment]
Ive added the webhook, so everything should work for now.
