### ISSUE TITLE
Possibility to change shown texts

### ISSUE THREAD

**Issue by hpvd** [Zeichen32/PiwikCustomOptOut#8]
Would be great if one could not only change the appearance (CSS) but also the 2 texts shown (marked or not) directly within this plugin.

With this function one could easily adopt this function when using piwik for sites with
- different languages
- different target groups (word choice and depth of given details for this function...)
- different types of designation (e.g. in German there is a "Sie" and "Du" for "You" depending on whom you're talking to..)

**Comment by Zeichen32** [comment]
Done in Version (0.2.0) https://github.com/Zeichen32/PiwikCustomOptOut/tree/0.2.0
